### ISSUE TITLE
feat: handle partition_limit

### ISSUE THREAD

**Issue by troycomi** [troycomi/reportseff#11]
Slurm can set time limit to `Partition_Limit` which breaks the time parsing.

Need to add partition as a required field, query slurm about each partition limit, then add a case to decode the time limit.

**Comment by blake-riley** [comment]
Just ran into this, came here to report, looks like you're already on top of it!
Thanks for the package!

**Comment by troycomi** [comment]
Could you (or someone) give me outputs for:
```
reportseff --format="+partition,qos" # will fail, but I need the sacct output
scontrol show partition
sacctmgr show qos format=name,maxwall
```
The system I work on doesn't have partition limits enabled so this is hard to develop.  Thanks!

**Comment by blake-riley** [comment]
I'm an untrained beginner when it comes to SLURM admin --- only beginning to bring up this cluster, so it's a pretty barebones config.
At the moment, I don't have partition limits enabled either.

FWIW, reportseff worked just fine, up until I cancelled job 341 that was launched through srun (see the State entry).
(Side note: I've just now set DefaultMemPerCPU...)

To directly answer your questions:

1. `reportseff --since d=1 -g --color --format="+partition,qos"`
```
Error processing entry: {'AdminComment': '', 'AllocCPUS': '1', 'Elapsed': '00:00:00', 'JobID': '341', 'JobIDRaw': '341', 'MaxRSS': '', 'NNodes': '1', 'Partition': 'mainqueue', 'QOS': 'normal', 'REQMEM': '4000G', 'State': 'CANCELLED by 1001', 'Timelimit': 'Partition_Limit', 'TotalCPU': '00:00:00'}
Traceback (most recent call last):
  File "/home/briley/.local/bin/reportseff", line 8, in <module>
    sys.exit(main())
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/console.py", line 97, in main
    output, entries = get_jobs(args)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/console.py", line 148, in get_jobs
    raise error
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/console.py", line 145, in get_jobs
    job_collection.process_entry(entry, add_job=add_jobs)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/job_collection.py", line 164, in process_entry
    self.jobs[job_id].update(entry)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/job.py", line 110, in update
    self._update_main_job(entry)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/job.py", line 130, in _update_main_job
    _parse_slurm_timedelta(entry["Timelimit"]) if "Timelimit" in entry else 1
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/job.py", line 337, in _parse_slurm_timedelta
    raise ValueError(f'Failed to parse time "{delta}"')
ValueError: Failed to parse time "Partition_Limit"
```

2. `scontrol show partition mainqueue`
```
PartitionName=mainqueue
   AllowGroups=ALL AllowAccounts=ALL AllowQos=ALL
   AllocNodes=ALL Default=YES QoS=N/A
   DefaultTime=NONE DisableRootJobs=NO ExclusiveUser=NO GraceTime=0 Hidden=NO
   MaxNodes=UNLIMITED MaxTime=UNLIMITED MinNodes=0 LLN=NO MaxCPUsPerNode=UNLIMITED
   Nodes=bignode
   PriorityJobFactor=1 PriorityTier=1 RootOnly=NO ReqResv=NO OverSubscribe=NO
   OverTimeLimit=NONE PreemptMode=OFF
   State=UP TotalCPUs=128 TotalNodes=1 SelectTypeParameters=NONE
   JobDefaults=(null)
   DefMemPerNode=UNLIMITED MaxMemPerNode=UNLIMITED
```

3. `sacctmgr show qos format=name,maxwall`
```
      Name     MaxWall
---------- -----------
    normal
```

**Comment by troycomi** [comment]
Ok, this should be enough to implement something but I don't have time for a few weeks (probably).

Just pushed a patch to ignore Partition_Limit (v2.2.4) and will close this once I implement the actual behavior.

Thanks for the help and patience!

**Comment by blake-riley** [comment]
No worries! Thanks for your work on the neat package!

Since you say "should be enough", I figured I'd give you a quick update. Hopefully this will help with your understanding.

Now running reportseff v2.2.4, and I've just put a MaxTime on the `mainqueue` partition, and then run `scontrol reconfigure`.

1. For `reportseff --since d=1 -g --color --format="+partition,qos" --debug`, the offending query returns
```
|1|00:00:00|341|341||1|mainqueue|normal|4000G|CANCELLED by 1001|Partition_Limit|00:00:00
```

2. The output of `scontrol show partition mainqueue` is the same except for:
> `MaxTime=10-00:00:00`

3. `sacctmgr show qos format=name,maxwall` hasn't changed.

**Comment by troycomi** [comment]
Just pushed v2.3.0 which should call scontrol to parse partition_limit.  I have unit tests with your input, but could someone verify it works on their system before I close this issue?

**Comment by blake-riley** [comment]
Sure, now running 2.3.0.

Can confirm that if a job _completes_, it picks up the Partition, and uses this to determine the correct timelimit, both UNLIMITED and e.g. 10-00:00:00.

However, I think you've inadvertently introduced a new (very small) bug.

If a job was cancelled, then "Partition" isn't included in the Entry dict.
```
Error processing entry: {'AdminComment': '', 'AllocCPUS': '1', 'Elapsed': '00:00:00', 'JobID': '348', 'JobIDRaw': '348', 'MaxRSS': '', 'NNodes': '1', 'REQMEM': '4000M', 'State': 'CANCELLED by 1001', 'Timelimit': 'Partition_Limit', 'TotalCPU': '00:00:00'}
Traceback (most recent call last):
  File "/home/briley/.local/bin/reportseff", line 8, in <module>
    sys.exit(main())
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/console.py", line 97, in main
    output, entries = get_jobs(args)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/console.py", line 149, in get_jobs
    raise error
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/console.py", line 146, in get_jobs
    job_collection.process_entry(entry, add_job=add_jobs)
  File "/home/briley/.local/pipx/venvs/reportseff/lib/python3.8/site-packages/reportseff/job_collection.py", line 170, in process_entry
    and entry["Partition"] in self.partition_timelimits
KeyError: 'Partition'
```
As far as I can tell, you've just gotta make sure you check `and "Partition" in entry` near the top of that if block.

Otherwise, thanks!

**Comment by troycomi** [comment]
Odd, I wouldn't think sacct would just leave that out for canceled jobs.  Maybe because it hasn't run at all?

Pushing a patch now (2.3.1), let me know if it's still broken or you find something new!

**Comment by blake-riley** [comment]
Yep, 2.3.1 works perfectly for my system.
I'll open another issue if I find something new!
Thanks!

**Comment by troycomi** [comment]
Great, thanks!
