### ISSUE TITLE
ValueError: Unknown comment type '{"a'

### ISSUE THREAD

**Issue by dev-zero** [troycomi/reportseff#12]
I run into the following issue with `reportseff 2.2.2` on NERSCs Perlmutter with `slurm 21.08.8-2`:
```
reportseff -u muellert
Error processing entry: {'AdminComment': '{"arrayTaskId":4294967294,"nodes":"nid006251","startTime":1661156816,"resizing":0,"jobExitCode":0,"timeLimit":240,"qos":"regular_1","submitTime":1661155410,"cluster":"perlmutter","batchHost":"nid006251","allocCpus":256,"tresRequest":"1=256,2=490000,3=18446744073709551614,4=1,5=256","reboot":0,"restartCnt":0,"argv":["run_perlmutter.sh"],"name":"run_perlmutter.sh","gresRequest":"cpu=256,mem=490000M,node=1,billing=256","packJobId":0,"arrayJobId":0,"priority":67701,"stdinPath":"\\/dev\\/null","jobDerivedExitCode":0,"allocNodes":1,"jobId":3045165,"jobAccount":"m3503","endTime":1661165977,"workingDirectory":"\\/global\\/homes\\/m\\/muellert\\/runs\\/deltatests\\/PBE-GPW-TZV2P\\/B.q3\\/1.00","partition":"regular_milan_ss11","features":"cpu","packJobOffset":0,"uid":98040}', 'AllocCPUS': '256', 'Elapsed': '02:32:41', 'JobID': '3045165', 'JobIDRaw': '3045165', 'MaxRSS': '', 'NNodes': '1', 'REQMEM': '490000M', 'State': 'COMPLETED', 'Timelimit': '04:00:00', 'TotalCPU': '21-10:28:51'}
Traceback (most recent call last):
  File "/global/homes/m/muellert/.local/bin/reportseff", line 8, in <module>
    sys.exit(main())
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/reportseff/console.py", line 97, in main
    output, entries = get_jobs(args)
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/reportseff/console.py", line 148, in get_jobs
    raise error
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/reportseff/console.py", line 145, in get_jobs
    job_collection.process_entry(entry, add_job=add_jobs)
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/reportseff/job_collection.py", line 164, in process_entry
    self.jobs[job_id].update(entry)
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/reportseff/job.py", line 110, in update
    self._update_main_job(entry)
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/reportseff/job.py", line 156, in _update_main_job
    self._parse_admin_comment(entry["AdminComment"])
  File "/global/u2/m/muellert/.local/pipx/venvs/reportseff/lib/python3.9/site-packages/reportseff/job.py", line 172, in _parse_admin_comment
    raise ValueError(f"Unknown comment type '{comment_type}'")
ValueError: Unknown comment type '{"a'
```

**Comment by troycomi** [comment]
Thanks for posting. I'm off this week but should be a quick fix. Glad you like the tool!
