### ISSUE TITLE
Division by zero if AllocCPUs is 0

### ISSUE THREAD

**Issue by tardigradus** [troycomi/reportseff#47]
I seemed to have managed to cancel a job before the CPU allocation had taken place, which left  ```AllocCPUs``` equal to zero and thus led to a `ZeroDivisionError`: 
````
$ reportseff --since 2023-10-16                                                                                                                                      
Error processing entry: {'AdminComment': '', 'AllocCPUS': '0', 'Elapsed': '00:00:00', 'JobID': '15053872_1491', 'JobIDRaw': '15055386', 'MaxRSS': '', 'NNodes': '1', 'REQMEM': '4G', 'State': 'CANCELLED by 324062', 'Timelimit': '04:00:00', 'TotalCPU': '00:00:00'}
Traceback (most recent call last):
  File "/home/loris/.local/bin/reportseff", line 8, in <module>
    sys.exit(main())
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/reportseff/console.py", line 97, in main
    output, entries = get_jobs(args)
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/reportseff/console.py", line 149, in get_jobs
    raise error
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/reportseff/console.py", line 146, in get_jobs
    job_collection.process_entry(entry, add_job=add_jobs)
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/reportseff/job_collection.py", line 175, in process_entry
    self.jobs[job_id].update(entry)
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/reportseff/job.py", line 110, in update
    self._update_main_job(entry)
  File "/home/loris/.local/pipx/venvs/reportseff/lib64/python3.6/site-packages/reportseff/job.py", line 147, in _update_main_job
    if "TotalCPU" in entry and "AllocCPUS" in entry
ZeroDivisionError: division by zero
````

**Comment by troycomi** [comment]
Should be a quick fix, I'll try to get to it in a day or two. 

Thanks for the report!

**Comment by troycomi** [comment]
Actually it seems like this was fixed in 2.7.6.  Can you update and try again?

**Comment by tardigradus** [comment]
OK, something seems messed up at my end:
```
$ pipx upgrade reportseff
reportseff is already at latest version 2.3.1 (location: /home/loris/.local/pipx/venvs/reportseff)
```
I'll try to find out why `pipx` is so reluctant to install the actual latest version.
